import TablaDocumentosReutilizable from "@/components/tablaDocumentosReutilizable"



const datos = [
    {
        id: "1",
        titulo: "Controles Operacionales",
        documentos: [
            { id: "doc1", titulo: "Control Operacional para el Uso Eficiente de la Energía Eléctrica.pdf" },
            { id: "doc2", titulo: "Control Operacional para el Uso Eficiente del Agua.pdf" },
            { id: "doc3", titulo: "Control Operacional para la Recoleccion de Residuos.pdf" },
        ],
    },
    {
        id: "2",
        titulo: "Documentos Mandatorios",
        documentos: [
            { id: "doc1", titulo: "Control de las Salidas No Conformes .pdf" },
            { id: "doc2", titulo: "Proceso Mandatorio Auditorías Internas .pdf" },
            { id: "doc3", titulo: "Proceso Mandatorio Información Documentada.pdf" },
            { id: "doc4", titulo: "Proceso Mandatorio No Conformidad y Acción Correctiva.pdf" },
            { id: "doc5", titulo: "Proceso Mandatorio Recursos de Segimiento y Medición.pdf" },
        ],
    },
    {
        id: "3",
        titulo: "Formatos",
        documentos: [
            { id: "doc1", titulo: "Formato de detección de necesidades.docx" },
            { id: "doc2", titulo: "Formato de detección de necesidades.pdf" },
            { id: "doc3", titulo: "__encuesta de satisfacción___.docx" },
            { id: "doc4", titulo: "1 ECIT01-R001_2024_FICHA TECNICA.pdf" },
            { id: "doc5", titulo: "1. PSIT01-R01A-FORMATO DE SOLICITUD DE ESTADIAS TSU.docx" },
            { id: "doc6", titulo: "1. PSIT01-R01-FORMATO DE SOLICITUD DE ESTADIAS ING-LIC.docx" },
            { id: "doc7", titulo: "1. PSIT03-R01-FORMATO DE CARTA DE PRESENTACIÓN.xlsx" },
            { id: "doc8", titulo: "1. PSITO2-R01-PROGRAMA AUTORIZADO DE VISITAS INDUSTRIALES.docx" },
            { id: "doc9", titulo: "1. REGISTRO SOLICITUD DE PLÁTICAS, CONFERENCIAS, TALLERES.docx" },
            { id: "doc10", titulo: "2 ECIT01-R002_2024_SIC_FORMATO DE LISTA ASISTENCIA.pdf" },
            { id: "doc11", titulo: "2. PSIT01-R02A-NOTIFICACIÓN DE ESPACIO DE ESTADÍA AL PE TSU.docx" },
            { id: "doc12", titulo: "2. PSIT01-R02-NOTIFICACIÓN DE ESPACIO DE ESTADÍA AL PE ING-LIC..docx" },
            { id: "doc13", titulo: "2. PSIT03-R02-ANEXO A SERVICIO SOCIAL.docx" },
            { id: "doc14", titulo: "2. PSITO2-R02-SOLICITUD DE VISITA INDUSTRIAL.docx" },
            { id: "doc15", titulo: "2. REGISTRO DE ASISTENCIA A PLÁTICAS, CONFERENCIAS, TALLERES.docx" },
            { id: "doc16", titulo: "3 ECIT01-R003_2024_SIC_LISTAS DE CURSOS IMPARTIDOS.pdf" },
            { id: "doc17", titulo: "3. PSIT01-R03A-CARTA DE ENTREVISTA DEL AP TSU.docx" },
            { id: "doc18", titulo: "3. PSIT01-R03-CARTA DE ENTREVISTA DEL AP ING-LIC.docx" },
            { id: "doc19", titulo: "3. PSIT02-R03-NOTIFICACIÓN DE VISITA INDUSTRIAL AL PE.docx" },
            { id: "doc20", titulo: "3. PSIT03-R03-CARTA DE PRESENTACIÓN A LA INSTANCIA.docx" },
            { id: "doc21", titulo: "4 ECIT01-R004_ENCUESTA DE SATISFACCION.pdf" },
            { id: "doc22", titulo: "4. PSIT01-R04A-CARTA DE ASIGNACIÓN DEL AP TSU.docx" },
            { id: "doc23", titulo: "4. PSIT01-R04-CARTA DE ASIGNACIÓN DEL AP ING-LIC.docx" },
            { id: "doc24", titulo: "4. PSIT02-R04-SOLICITUD DE AUTOBÚS.docx" },
            { id: "doc25", titulo: "4. PSIT03-R04-FORMATO DE CARTA DE ACEPTACIÓN DE SERVICIO SOCIAL.docx" },
            { id: "doc26", titulo: "5. ENTREVISTA INICIAL.docx" },
            { id: "doc27", titulo: "5. PSIT01-R05A-CARTA DE PRESENTACIÓN DEL AP TSU.docx" },
            { id: "doc28", titulo: "5. PSIT01-R05-CARTA DE PRESENTACIÓN DEL AP ING-LIC.docx" },
            { id: "doc29", titulo: "5. PSIT02-05-SOLICITUD DE AUTORIZACIÓN A LA SUBDIRECCIÓN DE UNIVERSIDADES.docx" },
            { id: "doc30", titulo: "5. PSIT03-R05-FORMATO DE REGISTRO DE HORAS.docx" },
            { id: "doc31", titulo: "6. CARNET DE CITAS.docx" },
            { id: "doc32", titulo: "6. PSIT01-06A-CARTA COMPROMISO AP TSU.docx" },
            { id: "doc33", titulo: "6. PSIT01-06-CARTA COMPROMISO AP ING-LIC.docx" },
            { id: "doc34", titulo: "6. PSIT02-R06-CARTA DE PRESENTACIÓN A LA EMPRESA.docx" },
            { id: "doc35", titulo: "6. PSIT03-R06-FORMATO DE CARTA DE TÉRMINO.docx" },
            { id: "doc36", titulo: "7. PSIT01-07A-CARTA DE ACEPTACIÓN DE LA EMPRESA TSU.docx" },
            { id: "doc37", titulo: "7. PSIT01-07-CARTA DE ACEPTACIÓN DE LA EMPRESA ING-LIC.docx" },
            { id: "doc38", titulo: "7. PSIT02-R07-REPORTE FINAL DE VISITAS INDUSTRIALES.docx" },
            { id: "doc39", titulo: "7. PSIT03-R07-CONSTANCIA DE LIBERACIÓN.docx" },
            { id: "doc40", titulo: "7. SEGUIMIENTO DE SESIONES (notas clinicas).docx" },
            { id: "doc41", titulo: "8. FICHA INFORMATIVA.docx" },
            { id: "doc42", titulo: "8. PSIT01-08A-FORMATO SOLICITUD DE CARTA DE TÉRMINO DE ESTADIA TSU.docx" },
            { id: "doc43", titulo: "8. PSIT01-08-FORMATO SOLICITUD DE CARTA DE TÉRMINO DE ESTADIA ING-LIC.docx" },
            { id: "doc44", titulo: "8. PSIT03-R08-REPORTE MESUAL DE SERVICIO SOCIAL.docx" },
            { id: "doc45", titulo: "9. Constancia de Asistencia.docx" },
            { id: "doc46", titulo: "9. PSIT01-09A-CARTA DE TÉRMINO DE ESTADÍA TSU.docx" },
            { id: "doc47", titulo: "9. PSIT01-09-CARTA DE TÉRMINO DE ESTADÍA ING-LIC.docx" },
            { id: "doc48", titulo: "9. PSIT03-R09-ENCUESTA DE SATISFACCIÓN DEL PROCESO.docx" },
            { id: "doc49", titulo: "10. ENCUESTA SERVICIO PSICOPEDAGÓGICO.docx" },
            { id: "doc50", titulo: "10. PSIT01-R10-INSTRUMENTO DE RETROALIMENTACIÓN PARA AP DE ESTADÍA.docx" },
            { id: "doc51", titulo: "10. PSIT03-R10-INSTRUMENTO DE RETROALIMENTACIÓN PARA PLÁTICAS DE SS.docx" },
            { id: "doc52", titulo: "11. PSIT01-R11-INSTRUMENTO DE RETROALIMENTACIÓN DEL EMPLEADOR (DESEMPEÑO DEL AP EN ESTADÍA).docx" },
            { id: "doc53", titulo: "12. PSIT01-R12-INSTRUMENTO DE RETROALIMENTACIÓN PARA PLÁTICAS DE ESTADÍA.docx" },
            { id: "doc54", titulo: "2024 Vales rmsg.xlsx" },
            { id: "doc55", titulo: "ACYD01.pdf" },
            { id: "doc56", titulo: "ACYD02.jpeg" },
            { id: "doc57", titulo: "ACYD03.jpeg" },
            { id: "doc58", titulo: "AUTOEVALUACION_CURSOS PLATICAS CONFERENCIAS SM 2024.docx" },
            { id: "doc59", titulo: "BITACORA CONSUMO DE ENERGÍA.xlsx" },
            { id: "doc60", titulo: "BITACORA EQUIPOS MAYOR CONSUMO AGUA.docx" },
            { id: "doc61", titulo: "BITACORA EQUIPOS MAYOR CONSUMO ENERGÍA ELÉCTRICA.docx" },
            { id: "doc62", titulo: "BITACURA DE RESIDUOS.xlsx" },
            { id: "doc63", titulo: "CARGA_HORARIA .xlsx" },
            { id: "doc64", titulo: "CARTA BAJO PROTESTA.docx" },
            { id: "doc65", titulo: "CARTA COMPROMISO (EXENCION 50%).docx" },
            { id: "doc66", titulo: "carta de aceptación.docx" },
            { id: "doc67", titulo: "Check List Actividad Tutorial.xlsx" },
            { id: "doc68", titulo: "CONCENTRADO_RECONOCIMIENTOS_PRENSA.xlsx" },
            { id: "doc69", titulo: "CUESTIONARIO SOCIOECONÓMICO UTTECAM.docx" },
            { id: "doc70", titulo: "CUESTIONARIO.docx" },
            { id: "doc71", titulo: "ENCUESTA DE SATISFACIÓN (1).xlsx" },
            { id: "doc72", titulo: "Encuesta de satisfacción SUIT02-R04 .docx" },
            { id: "doc73", titulo: "ENCUESTA DE SATISFACCION DEL SERVICIO MEDICO 2024.docx" },
            { id: "doc74", titulo: "ENCUESTA DE SATISFACIÓN FORMATO.xlsx" },
            { id: "doc75", titulo: "Encuesta de Satisfacción IT Acto Prot..docx" },
            { id: "doc76", titulo: "Encuesta de satisfacción.docx" },
            { id: "doc77", titulo: "ENCUESTA DE SATISFACIÓN.pdf" },
            { id: "doc78", titulo: "ENCUESTA SATISFACIÓN Aspirantes S.E.docx" },
            { id: "doc79", titulo: "ENCUESTA SATISFACCIÓN TRAMITE TITULO.docx" },
            { id: "doc80", titulo: "Encuesta_SATISFICÓN.docx" },
            { id: "doc81", titulo: "Entrega de reconocimientos_2024.xlsx" },
            { id: "doc82", titulo: "EVALUACIÓN DE LA SATISFACCIÓN DEL CLIENTE.pdf" },
            { id: "doc83", titulo: "EVALUACION DE PROVEEDOR.xlsx" },
            { id: "doc84", titulo: "EVALUACIÓN ESTADÍA (1).docx" },
            { id: "doc85", titulo: "FICHA INGRESO.docx" },
            { id: "doc86", titulo: "FICHA_PROTOCOLO_EVENTOS_V3.docx" },
            { id: "doc87", titulo: "FORMATO BAJA REGLAMENTARIA.docx" },
            { id: "doc88", titulo: "FORMATO DE ASIGNACIÓN INTERNA.docx" },
            { id: "doc89", titulo: "FORMATO DE ASIGNACIÓN DE ASESOR.docx" },
            { id: "doc90", titulo: "FORMATO DE BAJA VOLUNTARIA.docx" },
            { id: "doc91", titulo: "FORMATO DE REGISTRO DE ACTIVIDADES PERSONAL.pdf" },
            { id: "doc92", titulo: "FORMATO DE REGISTRO DE AIIDT.pdf" },
            { id: "doc93", titulo: "FORMATO DE REGISTRO Y CONTROL DE AVANCE DE ESTADÍA.xlsx" },
            { id: "doc94", titulo: "Formato de Requisición de Mat biblio..docx" },
            { id: "doc95", titulo: "FORMATO INFORME_DE_FIN_DE_CUATRIMESTRE.docx" },
            { id: "doc96", titulo: "Formato Presupuesto 2025.xlsx" },
            { id: "doc97", titulo: "formato quejas buzon..pdf" },
            { id: "doc98", titulo: "Formato req rmsg.xlsx" },
            { id: "doc99", titulo: "FORMATO SOLICITUD DE BECA DE EXENCIÓN.docx" },
            { id: "doc100", titulo: "FORMATO SOLICITUD_DE_CANALIZACION.docx" },
            { id: "doc101", titulo: "FORMATO_EXPEDIENTE ESTUDIANTE.xlsx" },
            { id: "doc102", titulo: "FORMATO_TUTORIA_INDIVIDUAL.xlsx" },
            { id: "doc103", titulo: "FORMATOS_SEGUIMIENTO ACCIONES REMEDIALES (1).xlsx" },
            { id: "doc104", titulo: "HORARIO_DOCENTE 1 .docx" },
            { id: "doc105", titulo: "HORARIO_GRUPO.docx" },
            { id: "doc106", titulo: "Indicador cuatrimestral.xlsx" },
            { id: "doc107", titulo: "Informe de INDICADORES DESEMPEÑO PIT 2024.xlsx" },
            { id: "doc108", titulo: "INFORME_CUATRIMESTRAL.xlsx" },
            { id: "doc109", titulo: "Lineamientos para la integración de expedientes 2024.docx" },
            { id: "doc110", titulo: "LISTA DE REGISTRO AGUA.doc" },
            { id: "doc111", titulo: "Lista de Registro Captación ADPR02-R01 ADPR02-R01.docx" },
            { id: "doc112", titulo: "Lista de Registro Captación ADPR02-R01.pdf" },
            { id: "doc113", titulo: "LISTA DE REGISTRO ENERGÍA.doc" },
            { id: "doc114", titulo: "LISTA DE REGISTRO MANTENIMIENTO.doc" },
            { id: "doc115", titulo: "LISTA DE REGISTROS GESTIÓN AMBIENTAL.doc" },
            { id: "doc116", titulo: "Lista de Servicios Académicos y de Apoyo al Estudiante.docx" },
            { id: "doc117", titulo: "LISTA_DE_ASISTENCIA .xls" },
            { id: "doc118", titulo: "MANUAL PROTOCOLO SERVICIO AL CLIENTE serv medico 2024.docx" },
            { id: "doc119", titulo: "MATRICES IT GESTIÓN AMBIENTAL INSTITUCIONAL.xlsx" },
            { id: "doc120", titulo: "Matrices SIG Mntto e Instalaciones.xlsx" },
            { id: "doc121", titulo: "MATRICES USO EFICIENTE AGUA.xlsx" },
            { id: "doc122", titulo: "Matriz de Comunicación SUIT02-R02.docx" },
            { id: "doc123", titulo: "Matriz de Requisitos legales ambientales.pdf" },
            { id: "doc124", titulo: "Matriz Institucional de Requisitos legales.pdf" },
            { id: "doc125", titulo: "Matriz requisitos legales.xlsx" },
            { id: "doc126", titulo: "MATRIZ ROLES Y RESPONSABILIDADES.pdf" },
            { id: "doc127", titulo: "MNIT05-R01 MATRIZ DE ASPECTOS AMBIENTALES FORMATO.xlsx" },
            { id: "doc128", titulo: "PEIT02-R10 INFORME DE COORDINADOR DE TUTORES.xlsx" },
            { id: "doc129", titulo: "Orden de trabajo.xlsx" },
            { id: "doc130", titulo: "PEIT02-R11 EXPEDIENTE DEL ALUMNO.xlsx" },
            { id: "doc131", titulo: "PGIT01 Cuestionario ok.pdf" },
            { id: "doc132", titulo: "PGIT01_Formato Edo Cta Pptal.pdf" },
            { id: "doc133", titulo: "PGIT02-R01 Aviso de comisión.pdf" },
            { id: "doc134", titulo: "PGIT02-R02 Infome de comisión.pdf" },
            { id: "doc135", titulo: "PGIT02-R03 Formato solicitud de transferencia.pdf" },
            { id: "doc136", titulo: "PGIT02-R04 Cuestionario.pdf" },
            { id: "doc137", titulo: "Plan de comunicación SUIT02-R01 .docx" },
            { id: "doc138", titulo: "Preguntas de encuesta de satisfacción de usuarios.xlsx" },
            { id: "doc139", titulo: "PROGRAMACION_Y_AVANCE_DE_TEMAS .doc" },
            { id: "doc140", titulo: "Registro de ALUMNOS ASIGNADOS.xlsx" },
            { id: "doc141", titulo: "REGISTRO DE CA y GI.pdf" },
            { id: "doc142", titulo: "REGISTRO_DE_ASESORIAS.doc" },
            { id: "doc143", titulo: "Relación para registro de servicio (1).xlsx" },
            { id: "doc144", titulo: "Reporte de la sesión grupal de tutoría_Formato y explicación del llenado.docx" },
            { id: "doc145", titulo: "Reporte de la sesión grupal de tutoría_Formato.docx" },
            { id: "doc146", titulo: "Reporte de Seguimiento Académico.docx" },
            { id: "doc147", titulo: "RETROALIMENTACION DE LA IT DE AIIDT.pdf" },
            { id: "doc148", titulo: "RHIT02-R01 Formato de detección de necesidades de capacitación.docx" },
            { id: "doc149", titulo: "RHIT02-R02 PROGRAMA DE CAPACITACIÓN.xlsx" },
            { id: "doc150", titulo: "RHIT02-R03 SOLICITUD_CURSOS.docx" },
            { id: "doc151", titulo: "RHIT02-R07_ FORMATO DE EVALUACIÓN DE CAPACITACIÓN SEMESTRAL.xlsx" },
            { id: "doc152", titulo: "RHIT02-RH04 Listas de Asistencia.pdf" },
            { id: "doc153", titulo: "RHIT02-RH05 Encuesta de Satisfaccion del Curso_2021.docx" },
            { id: "doc154", titulo: "RHIT02-RH06 Listas de Entrega de Constancias.docx" },
            { id: "doc155", titulo: "SMIT.01-04 Lista de Asistencia EVENTOS O CONFERENCIAS.xls" },
            { id: "doc156", titulo: "SMIT01-R01 HOJA DIARIA DE CONSULTA EXTERNA.xlsx" },
            { id: "doc157", titulo: "SMIT01-R02 CONSENTRADO MENSUAL DE CONSULTA.xlsx" },
            { id: "doc158", titulo: "SMIT01-R03 REGISTRO DE SOLICITUD DE CONFERENCIAS.xlsx" },
            { id: "doc159", titulo: "SMIT01-R05FORMATO DE ENVIO A LA UNIDAD DE APOYO PSICOPEDAGOGICO.docx" },
            { id: "doc160", titulo: "Solicitud de personal.docx" },
            { id: "doc161", titulo: "Solicitud de reconocimiento (1).xlsx" },
            { id: "doc162", titulo: "Solicitud.xlsx" },
            { id: "doc163", titulo: "SOLICITUD_DE_CANALIZACION.docx" },
            { id: "doc164", titulo: "STICIT01-R01 Formato de solicitud de servicio Rev 03.docx" },
            { id: "doc165", titulo: "STICIT01-R02 Formato de evaluacion Rev 03.docx" },
            { id: "doc166", titulo: "STICIT01-R03 Dictamen Rev 03.docx" },
            { id: "doc167", titulo: "STICIT01-R04 Formato de liberacion de servicio externo Rev 03.docx" },
            { id: "doc168", titulo: "STICIT01-R05 Plan de mantenimiento Rev 03.docx" },
            { id: "doc169", titulo: "Tarjeta de préstamo.pdf" },
            { id: "doc170", titulo: "TUTORIA_GRUPAL PEIT02-R07.docx" },
            { id: "doc171", titulo: "TUTORIA_GRUPAL.docx" },
            { id: "doc172", titulo: "VERIFICACION_Y_SEGUIMIENTO.docx" }
        ],
    },
    {
        id: "4",
        titulo: "Instrucciones de trabajo",
        documentos: [
            { id: "doc1", titulo: "IT Gestión de Quejas y Sugerencias.pdf" },
            { id: "doc2", titulo: "IT Actividades Culturales y Deportivas.pdf" },
            { id: "doc3", titulo: "IT Actividades de Extension Universitaria.pdf" },
            { id: "doc4", titulo: "IT Actividades de Investigación, Innovación y Desarrollo Tecnologico.pdf" },
            { id: "doc5", titulo: "IT Acto Protocolario.pdf" },
            { id: "doc6", titulo: "IT Administración del Proceso Enseñanza Apredizaje.pdf" },
            { id: "doc7", titulo: "IT Adquisición de Materiales.pdf" },
            { id: "doc8", titulo: "IT Apoyo Psicopedagógico.pdf" },
            { id: "doc9", titulo: "IT Asignación Presupuestal.pdf" },
            { id: "doc10", titulo: "IT Asignación y Comprobación de Viaticos.pdf" },
            { id: "doc11", titulo: "IT Asignación y seguimiento de estadias.pdf" },
            { id: "doc12", titulo: "IT Atención y Preservación de la Salud.pdf" },
            { id: "doc13", titulo: "It Bolsa de Trabajo.pdf" },
            { id: "doc14", titulo: "IT Capacitación .pdf" },
            { id: "doc15", titulo: "IT Captación de Aspirantes.pdf" },
            { id: "doc16", titulo: "IT Coordinación del Programa Institucional de Tutorias.pdf" },
            { id: "doc17", titulo: "IT DESEMPEÑO DE EGRESADOS.pdf" },
            { id: "doc18", titulo: "IT Difusión y Divulgación .pdf" },
            { id: "doc19", titulo: "IT Educcion Continua.pdf" },
            { id: "doc20", titulo: "IT Evaluación de los Servicios Académicos y de Apoyo a los Estudiantes.pdf" },
            { id: "doc21", titulo: "IT Gestión de Estadias.pdf" },
            { id: "doc22", titulo: "IT Gestión de Visitas Industriales.pdf" },
            { id: "doc23", titulo: "IT Inscripción de Estudiantes.pdf" },
            { id: "doc24", titulo: "IT Mantenimiento a Instalaciones e Infraestructura.pdf" },
            { id: "doc25", titulo: "IT Medios de Expresión .pdf" },
            { id: "doc26", titulo: "IT Prestamo de Auditorios para la realización de eventos institucionales .pdf" },
            { id: "doc27", titulo: "IT Prestamo y control de unidades del parque vehicular.pdf" },
            { id: "doc28", titulo: "IT PROGRAMACIÓN CUATRIMESTRAL.pdf" },
            { id: "doc29", titulo: "IT Reclutamiento, Selección y Contratación de Personal.pdf" },
            { id: "doc30", titulo: "IT Requisitos Legales.pdf" },
            { id: "doc31", titulo: "IT Seguimiento a Convocatorias de Becas Internas y Externas para Estudiaantes.pdf" },
            { id: "doc32", titulo: "IT Servicio Social.pdf" },
            { id: "doc33", titulo: "IT Servicios Bibliotecarios.pdf" },
            { id: "doc34", titulo: "IT Servicios Tecnologicos.pdf" },
            { id: "doc35", titulo: "IT Servicios TIC.pdf" },
            { id: "doc36", titulo: "IT Sistema de Gestión Ambiental Institucional.pdf" },
            { id: "doc37", titulo: "IT Solicitud y Expedición de Cheques y-o Transferencia.pdf" },
            { id: "doc38", titulo: "IT Tramite de Titulo Profesional Electronico.pdf" },
            { id: "doc39", titulo: "Procedimiento para el funcionamiento del Comité de Control y Desempeño Institucional.pdf" },
            { id: "doc40", titulo: "Protocolo de Acción Situaciones Potenciales de Emergencia.pdf" }
            ],
    },
]
export default function Sigc() {
    return (
        <TablaDocumentosReutilizable
            secciones={datos}
            titulo="Sistema de Gestión de la Calidad"
            descripcion="Explora los productos de investigación generados por la comunidad académica de la institución, organizados por año y tipo de documento."
        />
    )
}
